// Auto-generated by `mix routes.gen` — do not edit manually.
//
// Typed path builders mirroring the browser-facing routes in
// ElixirReactStarterWeb.Router. Phoenix 1.7+ has no named route helpers
// (the ~p sigil replaced them), so what is exported is the route *table*
// ~p validates against: one builder per distinct path, with :param
// segments as required typed args and an optional query object.
//
// Regenerated on `mix assets.build` / `assets.deploy` and the dev watcher;
// `mix routes.gen --check` (in `mix precommit`) fails the build if this
// file ever drifts from the router.

type QueryValue = string | number | boolean | null | undefined;
type QueryParams = Record<string, QueryValue | QueryValue[]>;

function query(params?: QueryParams): string {
  if (!params) return '';
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value === null || value === undefined) continue;
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item !== null && item !== undefined) search.append(key, String(item));
      }
    } else {
      search.append(key, String(value));
    }
  }
  const qs = search.toString();
  return qs ? `?${qs}` : '';
}

export const routes = {
  confirmEmail: (q?: QueryParams) => `/confirm-email${query(q)}`,
  dashboard: (q?: QueryParams) => `/dashboard${query(q)}`,
  forgotPassword: (q?: QueryParams) => `/forgot-password${query(q)}`,
  locale: (q?: QueryParams) => `/locale${query(q)}`,
  login: (q?: QueryParams) => `/login${query(q)}`,
  logout: (q?: QueryParams) => `/logout${query(q)}`,
  register: (q?: QueryParams) => `/register${query(q)}`,
  resendConfirmation: (q?: QueryParams) => `/resend-confirmation${query(q)}`,
  resetPassword: (q?: QueryParams) => `/reset-password${query(q)}`,
  root: (q?: QueryParams) => `/${query(q)}`,
  settings: (q?: QueryParams) => `/settings${query(q)}`,
  settingsAccount: (q?: QueryParams) => `/settings/account${query(q)}`,
  settingsEmail: (q?: QueryParams) => `/settings/email${query(q)}`,
  settingsEmailApplyChange: (q?: QueryParams) => `/settings/email/apply-change${query(q)}`,
  settingsPassword: (q?: QueryParams) => `/settings/password${query(q)}`,
} as const;

export type RouteName = keyof typeof routes;
