import { test as base, expect as baseExpect, type Page } from '@playwright/test';
import { go } from '../js/result';

/**
 * Suite-wide Playwright fixtures.
 *
 * Specs `import { expect, test } from '../fixtures'` (never directly from
 * `@playwright/test`). Two things happen for every test without the spec
 * asking:
 *
 * 1. **Its accounts are deleted when it ends**, pass or fail. Every email
 *    `uniqueEmail` (helpers.ts) generates during a test is recorded, and the
 *    `cleanup` fixture sends them to `DELETE /dev/e2e/users` afterwards, so a
 *    run leaves nothing behind and no test ever sees another's accounts.
 *
 * 2. **Hydration before interaction.** `page.goto` waits for client-side
 *    hydration (see assets/js/app-providers.tsx for the matching signal).
 *    Every page is server-rendered: until React has mounted, controlled
 *    inputs haven't reconciled with the SSR markup and form handlers aren't
 *    attached, so a `fill` and a click quietly hit the native path and the
 *    form "does nothing". Later navigation goes through Inertia with the
 *    app still mounted, so no further waits are needed.
 */

// Emails generated by the running test. A worker runs one test at a time,
// so a module-level list is per test; `cleanup` drains it.
const generatedEmails: string[] = [];

/** Records an email so the account behind it is deleted after the test. */
export function trackEmail(email: string): void {
  generatedEmails.push(email);
}

// What a page reported while loading: script errors, failed requests and
// server errors. Kept per page, so a page that never hydrates can say why
// instead of only timing out.
const diagnostics = new WeakMap<Page, string[]>();

function watch(page: Page): void {
  if (diagnostics.has(page)) {
    return;
  }
  const notes: string[] = [];
  diagnostics.set(page, notes);
  page.on('pageerror', (error) => notes.push(`page error: ${error.message}`));
  page.on('console', (msg) => {
    if (msg.type() === 'error') {
      notes.push(`console error: ${msg.text()}`);
    }
  });
  page.on('requestfailed', (req) => notes.push(`request failed: ${req.url()} (${req.failure()?.errorText})`));
  page.on('response', (res) => {
    const failed = res.status() >= 500 || (res.status() >= 400 && res.url().includes('/assets/'));
    if (failed) {
      notes.push(`HTTP ${res.status()}: ${res.request().method()} ${res.url()}`);
    }
  });
}

/**
 * Waits until React has hydrated the page. `page.goto` on the test's own
 * `page` already does this; a second page (another tab, or another browser
 * context for a second person) calls it after navigating.
 */
export async function waitForHydration(page: Page): Promise<void> {
  watch(page);
  // Bounded like a navigation, not like a click: on a busy machine the
  // first load of a page's code (or the dev server recompiling) can take
  // longer than any single action should.
  const [error] = await go(() =>
    page.waitForSelector('html[data-hydrated="true"]', { state: 'attached', timeout: 45_000 })
  );
  if (!error) {
    return;
  }
  const notes = diagnostics.get(page) ?? [];
  const report =
    notes.length > 0
      ? `While loading, the page reported:\n  ${notes.slice(-15).join('\n  ')}`
      : 'It reported no errors.';
  throw new Error(`${page.url()} never hydrated.\n${report}`, { cause: error });
}

function deleteAccounts(baseURL: string | undefined, emails: string[]): Promise<Response> {
  return fetch(new URL('/dev/e2e/users', baseURL), {
    method: 'DELETE',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ emails }),
  });
}

export const test = base.extend<{ cleanup: undefined }>({
  // Plain fetch, not a Playwright request context: a context made here is
  // traced as part of the test, and its trace files can be gone by the time
  // this teardown runs, failing a test that passed.
  cleanup: [
    async ({ baseURL }, use) => {
      generatedEmails.length = 0;
      await use(undefined);

      const emails = generatedEmails.splice(0);
      if (emails.length === 0) {
        return;
      }
      const [error, response] = await go(() => deleteAccounts(baseURL, emails));
      if (error) {
        throw new Error(`deleting the test's accounts failed: ${error.message}`, { cause: error });
      }
      baseExpect(response.ok, `deleting the test's accounts failed: ${response.status}`).toBe(true);
    },
    { auto: true },
  ],

  page: async ({ page }, use) => {
    watch(page);
    const originalGoto = page.goto.bind(page);
    page.goto = async (url, opts) => {
      const response = await originalGoto(url, opts);
      await waitForHydration(page);
      return response;
    };
    await use(page);
  },
});

export const expect = baseExpect;
